### PR TITLE
Moved to previous version and fixed errors in https://eventyay.com/ap…

### LINKED ISSUE #1468: Autogeneration from API not working
There is an organizer who tries to generate an app with the API https://eventyay.com/api/v1/events/257 on https://webgen.eventyay.com/

The generation stops at 50% on http://opev-webgen-dev.herokuapp.com/

### PR DESCRIPTION
**Pull request by agbilotia1998**
…i/v1/events/257 app generation

Fixes #1468 

Changes:Supports old version APIs and fixed event creation for https://eventyay.com/api/v1/events/257

Review Link:
https://openeveweb.herokuapp.com/

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@Princu7 @geekyd please review.

File: src/backend/generator.js [hunk 1]
```diff
@@ -314,7 +314,7 @@ exports.createDistDir = function(req, socket, callback) {
           distHelper.optimizeLogo(logoPath, socket, function(err, pad) {
             if(err) {
               console.log(err);
-              return done(err);
+              //return done(err);
```
Comment (geekyd) [inline src/backend/generator.js]: @agbilotia1998 This is not the correct solution here, seems like the `logoPath` is missing. Please handle the case when there is no logo instead of commenting the code

**Comment by agbilotia1998** [comment]
@geekyd please review.
