### PR TITLE
Increase the quality of the logo output by the generator

### LINKED ISSUE #1411: Ensure that the resized logo is of a better quality
**Actual Behaviour**
The logo generated by the webapp looks in poor quality, especially on higher end displays.

**Expected Behaviour**

The logo should look sharp and not blurred.

**Steps to reproduce it**
This problem has been discussed in detail [here](https://github.com/fossasia/open-event/pull/189).

Some screenshots to compare. Zoom in to see the problem more clearly

* Manually updated logo
Manual

* Logo Output from generator
Generator

**Would you like to work on the issue?**
Yes. Working on it. Will send a PR soon. Thanks :)

### PR DESCRIPTION
**Pull request by Princu7**
Fixes #1411 

Changes:
* Increase the quality of the logo output by the generator

Screenshots for the change: 
Check it here  https://mahikaw.github.io/PyCon2017/

@aayusharora @geekyd @sumedh123 @mahikaw @arp95 Please review. Thanks :)

### CODE REVIEW

File: src/backend/dist.js [hunk 1]
```diff
@@ -150,7 +151,9 @@ var optimizeLogo = function(image, socket, done) {
       diffHeight = 45 - height;
       padding = padding + (diffHeight)/2;
     }
+    var qualityMultiplier = 4;
 
+    width = width * qualityMultiplier; height = height * qualityMultiplier;
```
Comment (sumedh123) [inline src/backend/dist.js]: Can we set the variables on different lines? Just to maintain cleaner code.

Comment (Princu7) [inline src/backend/dist.js]: Yes. Will make the changes. Thanks for pointing it out :)

**Comment by Princu7** [comment]
@sumedh123 @geekyd Performed changes. Please review again. Thanks :)
