### PR TITLE
Fixes download of large size background image

### LINKED ISSUE #2082: Event picture converted to very large PNG and not showing up on main page
Using the API on https://eventyay.com/api/v1/events/641 does not generate a zip with a proper event picture. Instead there is a very large PNG in the folder that is not showing up.

### PR DESCRIPTION
**Pull request by agbilotia1998**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.

#### Short description of what this resolves:
Fixes download of large size background image.

Screenshot:
screenshot_2018-08-23 jugaadfest

Test Link: https://open-event-webapp.herokuapp.com/

Fixes #2082

### CODE REVIEW

File: src/backend/dist.js [hunk 1]
```diff
@@ -26,14 +26,14 @@ const downloadFile = function(url, file_path, next) {
   });
 
   fileStream.on('finish', function() {
+    next();
```
Comment (joeytwiddle) [inline src/backend/dist.js]: You might also want to call `next()` inside the `catch` below, if you want the process to continue after an error, instead of stalling.

Alternatively you could call `next(err)` from the catch, if you want to pass the error back for the caller to handle, in which case you shouldn't really need to log here.
