### PR TITLE
fixed #956 App crashes when invalid zip

### LINKED ISSUE #956: App crashes when invalid zip is uploaded
Web app crashes if the uploaded zip file is invalid (not contains required folders and files).

Steps to reproduce:

1. Go to app homepage
2. Upload any zip that does not contains /sessions or  /speakers or /event or other folders.
3. Click generate webapp
4. You can see app crashing in server logs.

error

I would like to work on this and submit a PR soon.
`

### PR DESCRIPTION
**Pull request by uttpal**
Fixes #956 app crashing if uploaded zip is invalid and not contains required json or files. 
Live Demo - https://openevent-app.herokuapp.com/

### CODE REVIEW

File: src/backend/generator.js [hunk 1]
```diff
@@ -241,11 +246,20 @@ exports.createDistDir = function(req, socket, callback) {
       console.log('================================WRITING\n');
       if (emit) socket.emit('live.process', {donePercent: 70, status: "Compiling the HTML pages from templates" });
 
-      getJsonData(req.body, function(data) {
+      getJsonData(req.body, function(error, data) {
+        if (error) {
+          console.log('Error Invalid Zip');
```
Comment (poush) [inline src/backend/generator.js]: I think you can better add this message on a log file.

**Comment by Princu7** [comment]
@uttpal Good work. Works great. Thanks!!

File: src/backend/generator.js (hunk 1 above)
Comment (Princu7) [inline src/backend/generator.js]: @poush Thanks for the review. The error message has already been added to the error logs.
